backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: meta
    label: Meta
    files:
      - name: tags
        label: Tags
        file: _data/tags.yml
        fields:
          - name: tags
            label: Tags
            widget: list
            fields: [{ name: tag, label: Tag }]

  - name: "faq"
    label: "FAQ"
    folder: src/pages/faq
    format: "json"
    extension: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Question", name: "title", widget: "string"}
      - {label: "Answer", name: "answer", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "relation", collection: "partners", searchFields: ["name"], valueField: "name"}
      - {
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: [
              { label: "Cat A", value: "A" },
              { label: "Cat B", value: "B" },
              { label: "Cat C", value: "C" }
          ]
        }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - { name: "tags", label: "Tags", widget: "relation", collection: "meta", entry: "tags", searchFields: ["tags"], valueField: "tags", multiselect: true }
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "partners"
        label: "Partners"
        file: "_data/partners.yml"
        description: "Partners"
        editor:
          preview: false
        fields:
          - name: partners
            label: Partners
            label_singular: "Partner"
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Description", description: "describe it", name: "description", widget: "string", required: false}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/product/product.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/products"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
